### ISSUE TITLE
Radio doesn't work well

### ISSUE THREAD

**Issue by chaosfreak93** [deluvas1911/saltychat-altv#1]
SaltyChat: 2.2.2

No Radio activate sound and no TeamSpeak response.
Other Users cannot hear me.

**Comment by LorianAtashi01** [comment]
You need to give us more information about that otherwise we can not help you and find out if it is a problem on the side of your code or our code

**Comment by chaosfreak93** [comment]
I tried it with 2.2.0 too and it worked perfectly. But which information do you need?

**Comment by LorianAtashi01** [comment]
How exactly do you integrade the Radio options in to your Gamemode, are you using Radiotowers for the Radio, which type of radioRange are you using, is the Channel Name that you pasted a string 
and one of the important things: Did you read the Wiki where it says that you have to trigger alt.emit("SaltyChat:EnablePlayer", player) on your Gamemode?

**Comment by deluvas1911** [comment]
And what version of the code are you using? The radio still had a few issues, which were fixed in the commits from 7 hours ago.

**Comment by chaosfreak93** [comment]
> And what version of the code are you using? The radio still had a few issues, which were fixed in the commits from 7 hours ago.

I use the latest version 1.0.2

**Comment by chaosfreak93** [comment]
> How exactly do you integrade the Radio options in to your Gamemode, are you using Radiotowers for the Radio, which type of radioRange are you using, is the Channel Name that you pasted a string
> and one of the important things: Did you read the Wiki where it says that you have to trigger alt.emit("SaltyChat:EnablePlayer", player) on your Gamemode?

radioRange I tried all and only longRange works sometimes on 2.2.2.
Yes I trigger alt.emit("SaltyChat:EnablePlayer", player) on join and i readed the wiki.
For test purposes I add the player on join to a radio channel. The channel is called "test".

When a player hold down the M Key i trigger this code: 
`alt.emit("SaltyChat:ToggleRadioSpeaker");
 alt.emit("SaltyChat:UseRadio", true, true);` and when he release the key i run this code: 
 `alt.emit("SaltyChat:UseRadio", true, false);
 alt.emit("SaltyChat:ToggleRadioSpeaker");`

**Comment by chaosfreak93** [comment]
Ah and Radio Towers doesn't work. So I don't use Radio Towers

**Comment by younesdev123** [comment]
`SaltyChat:ToggleRadioSpeaker`
It just serves you to activate the speaker mode, when you just want to talk on the radio you just have to send
`alt.emit("SaltyChat:UseRadio", isPrimary, isSending);`

**Comment by deluvas1911** [comment]
Issue has been resolved during discord troubleshooting.
- documentation of the radio has been improved
- radio tower bug fixed in version 1.0.3

Thanks for the feedback and for the support to fix the bug @younesdev123 and @chaosfreak93.
