### ISSUE TITLE
Microstutters

### ISSUE THREAD

**Issue by ghost** [deluvas1911/saltychat-altv#10]
Hey,
a lot of other players, including me, are getting microstutters nearly all the time (about every 0.5 seconds or so) when playing with SaltyChat on altV. When there are only about 200 players or more it's starting to stutter.

In my Teamspeak Logs there is this error filling thousands of lines:
`2021-09-04 20:06:36.672957|ERROR   |Salty Chat    |6  |Non-executable message: {"Command":6,"ServerUniqueIdentifier":"[CENSORED]","Parameter":{"IsMicrophoneMuted":true,"IsMicrophoneEnabled":false,"IsSoundMuted":false,"IsSoundEnabled":false}}`

Maybe you can help fixing this issue.

**Comment by deluvas1911** [comment]
Provide an extensive log (https://github.com/v10networkscom/saltychat-docs/blob/master/faq.md#how-to-enable-extensive-logging) from the session and the alt:V client log file .
You can send them to me by dm in discord (deluvas1911#6462)

**Comment by deluvas1911** [comment]
Server isn't using my plugin
