### ISSUE TITLE
TS3 Plugin Version 3.X.X Problem

### ISSUE THREAD

**Issue by Maxos-programming** [deluvas1911/saltychat-altv#12]
Since the plugin Update User cant Talk / no voice Aktivation in the Ingame Voice Channel.

Sideeffects: Swiss Channel works as usual.

Problem Can be validated with the Plugin Verison 2.3.6

**Comment by LorianAtashi01** [comment]
This is because there is no update released for this resource to the 3.X.X Plugin Update.
I'm currently working on releasing that on Monday or Tuesday. Thank you for the issue and your patience.

**Comment by ghost** [comment]
Same Problem. Waiting patiently ;)

**Comment by deluvas1911** [comment]
Enjoy waiting :D

**Comment by ghost** [comment]
Doin'my best... Hope that it will happen soon(tm)

**Comment by V4M0N0S** [comment]
.soon(tm)

**Comment by xx7eVeN** [comment]
Hey, any idea what happened with this? Seems due for a long time now.

**Comment by xx7eVeN** [comment]
I am wondering what happened to saltychat since deluvas gave it away - will it be maintained at any chance? This is a 15 minute change..

**Comment by LorianAtashi01** [comment]
> I am wondering what happened to saltychat since deluvas gave it away - will it be maintained at any chance? This is a 15 minute change..

I know it was only a 15 minute change. I was busy with exams that's why. Doing it right now.

**Comment by LorianAtashi01** [comment]
> Enjoy waiting :D

I think they enjoyed it :)

**Comment by V4M0N0S** [comment]
your done? :D

**Comment by LorianAtashi01** [comment]
> your done? :D

There is still one Problem with Radios. I'm on it right now

**Comment by V4M0N0S** [comment]
i trust in you bro <3

**Comment by LorianAtashi01** [comment]
Since we updated the minor things for 3.x.x, i'm gonna close this issue.
