### ISSUE TITLE
Phone not hanging up

### ISSUE THREAD

**Issue by CeyKie** [deluvas1911/saltychat-altv#14]
**Version**
3.0.5

**Describe the bug**
Call is not ending after hanging up.

**Usage of the code**
We use the newest version of SaltyChat. 

**To Reproduce**
1. Call any user
2. Hang up
3. You can still hear each other.

**Expected behavior**
The other player cannot be heard anymore.

**Comment by LorianAtashi01** [comment]
i will take a look at it.

**Comment by CrazyKee** [comment]
Same problem and specifications here.

**Comment by shaunluedeke** [comment]
the error is in the Voice Manager.cs class the list _phoneCalls has no check of who the caller is

**Comment by shaunluedeke** [comment]
http://37.114.32.239/fix.html this is a fix from me

**Comment by Phill030** [comment]
If this fix is not a workaround, please create a pull request with additional information

**Comment by Sheytan1337** [comment]
Does anyone already have a fix ?

**Comment by Phill030** [comment]
We are working on a fix asap

**Comment by Xantron** [comment]
Same Problem here…

**Comment by LorianAtashi01** [comment]
This issue should be now fixed
