### ISSUE TITLE
Whisper Problem

### ISSUE THREAD

**Issue by Xantron** [deluvas1911/saltychat-altv#15]
**Version**
3.0.5

**Describe the bug**
 Normal talking seems to work through Whisper as well. If you talk to someone, it opens the Whisper history in TeamSpeak. If you turn off the power for Whisper in TeamSpeak, so that Whisper no longer works, you can no longer talk to the player opposite.

**Usage of the code**
/

**To Reproduce**
1. Implement 1.2.3 from Phill030 to the alt:V Server
2. Use Client Version 3.0.5
3. Speak with a other Player in your near

**Expected behavior**
Normal Voice about TeamSpeak, not Whisper. Whisper only with Cellphone and Radio

**Screenshots / Logs**
https://media.discordapp.net/attachments/930510524016394331/930519386006110258/unknown.png

**Additional context**
/

**Comment by Phill030** [comment]
Should be fixed by now!
