### ISSUE TITLE
There is an File missing in the Resource folder

### ISSUE THREAD

**Issue by D4TENSCHLEUDERK4ZE** [deluvas1911/saltychat-altv#19]
https://gyazo.com/743dc091c17dbece63146645dc6eddb7

The JavaScript version.

**Comment by LorianAtashi01** [comment]
Maybe you have done something wrong while installing the resource to your server. The file should be there. See the Link:
https://github.com/Salt-V/saltychat-altv/blob/master/SaltyChat.Client/source/Models/SaltyChat/RadioChannelMemberUpdate.ts

**Comment by D4TENSCHLEUDERK4ZE** [comment]
But it is not in the Resource Folder. 
https://github.com/Salt-V/saltychat-altv/tree/master/Resource/Client/Models/SaltyChat

**Comment by LorianAtashi01** [comment]
I see. Please make sure to download the Resource from the Releases-Section on this Repo. I will check if it is also missing in the release and add it to it if the case is given.
