### ISSUE TITLE
Players are not unmuted

### ISSUE THREAD

**Issue by Lennart-1337** [deluvas1911/saltychat-altv#2]
**Version**
1.0.4

**Describe the bug**
Players are not unmuted to others (The other player hears the person). This phenomenon occurs randomly and can only be reproduced by chance.

**Usage of the code**
Just alt.emit("SaltyChat:EnablePlayer", player)

**To Reproduce**
1. Just try

**Expected behavior**
You should be able to hear other players

**Comment by deluvas1911** [comment]
Haven't managed yet reproducing it. Can you manage somehow to reproduce it and provide SaltyChat extensive logs?

**Comment by Letsion** [comment]
@deluvas1911 I think he can not 😅

**Comment by LorianAtashi01** [comment]
gonna close the issue because the creator of the issue is not answering anymore
