### ISSUE TITLE
command 4: pong is throwing a client exception

### ISSUE THREAD

**Issue by nbreakery** [deluvas1911/saltychat-altv#4]
**Version**
As of 14.06.2021, the prebuilt 1.07E2 was used and both configuration files were altered to fit my setup with ValeaRP script. (Quite problematic, sorry for that)

**Describe the bug**
After spawning, the teamspeak user gets moved to ingame channel, _but no command 4: pong? is being answered._
Updating voice range is not possible via the key, which was working on a 2.2.5 serverside before. 
After 6s, the teamspeak user is moved out of ingame-channel.

**Usage of the code**
The standard and well know parts of hud.js in ValeaRP. I can provide them, if needed.

**To Reproduce**
Get ValeaRP running, click "Letzte Position" to spawn and check the teamspeak log.

**Expected behavior**
Pong should be answered I guess?

**Screenshots / Logs**
Teamspeak + Salty extensive debug log:
[ts3client_2021-06-14__03_51_28.096333.log](https://github.com/deluvas1911/saltychat-altv/files/6645260/ts3client_2021-06-14__03_51_28.096333.log)
alt:V client log shows SaltyClient loaded succesfully and only one output line:
`[04:38:46][Error] "{\"Error\":3,\"Message\":null,\"ServerIdentifier\":null}"`

- SaltyChat in extensive logging mode done
- AltV client logs 

**Additional context**
Is this behaviour the result of a non-implemented pong response server-side?

**Comment by LeCyreaxYT** [comment]
Hey, the Problem is you need to implement the Hotkey for Voice Range Self. The Events for Microphone state and the Event on Voice Range changes has Otter Events Name as in Valea you need to edit this to get it work.

I have got SaltyChat to working Valea.

**Comment by deluvas1911** [comment]
As @LeCyreaxYT said you need to trigger the voice range change yourself. Check out the [wiki](https://github.com/deluvas1911/saltychat-altv/wiki/Events:-Client#saltychattogglerange) in the events section how to do that.
Can you replace the app.js in the Client directory with [this](https://github.com/deluvas1911/saltychat-altv/files/6646010/app.zip) one and check if it fixes it?

**Comment by deluvas1911** [comment]
@nbreakery
Fix for pong command was tested with elPadros and confirmed working. 
Correctly using the voice range change event isn't any issue of this script. If you need any help implementing the voice range change event, ask elPadros for my discord name and give me an DM.
