### ISSUE TITLE
Neuste Version und Server startet nicht richtig...

### ISSUE THREAD

**Issue by dev-mb** [deluvas1911/saltychat-altv#9]
Servus,

gerade die neuste Version heruntergeladen und man wollte den Server Starten und sobald SaltyChat Client geladen wird stürzt der Server ab ohne Fehler oder etc.

Kommentiert man SaltyChat aus startet der Server ganz normal aber halt ohne Salty...

**Comment by chaosfreak93** [comment]
[Die](https://github.com/deluvas1911/saltychat-altv/releases/tag/1.2.0) Version?

**Comment by dev-mb** [comment]
jap

**Comment by dev-mb** [comment]
aber jetzt anderes Problem

**Comment by dev-mb** [comment]
```
Loading resource SaltyClient
< ==== UNHANDLED EXCEPTION ==== > 

 Received an unhandled exception from : System.MissingMethodException: Method not found: 'AltV.Net.Function AltV.Net.Alt.OnServer(System.String, System.Action`2<!!0,!!1>)'.

   at SaltyChat.Server.VoiceManager..ctor()

   at SaltyChat.Server.Voice.OnStart() in C:\AltV-Testserver\Mappe - Visual Studio\Altv-Roleplay\SaltyServer\Voice.cs:line 9
```

**Comment by chaosfreak93** [comment]
Nutz doch bitte die [Pre-Built](https://github.com/deluvas1911/saltychat-altv/releases/tag/1.2.0) Version und Compile dies nicht selber. Ich und viel andere haben kein Problem mit der neusten SaltyChat Version^^

**Comment by dev-mb** [comment]
jetzt funktioniert es alles gut waren dumme Fehler...
